### PR TITLE
fix: Remove key from delete cache upon write

### LINKED ISSUE #65: Deleting a key from DB and writing it again in the same transaction does not work
Imagine key X is stored in the database. If we start a new transaction in which we will delete X, and later in the same transaction write X to the database again. The key will not be stored in the database.

```java
@Test
public void shouldWriteKeyAfterDeletion() {
    // given
    oneKey.wrapLong(1);
    oneValue.wrapLong(-1);
    oneColumnFamily.put(oneKey, oneValue);

    // when
    assertThat(oneColumnFamily.get(oneKey).getValue()).isEqualTo(-1);
    transactionContext.runInTransaction(
        () -> {
          oneColumnFamily.delete(oneKey);
          oneValue.wrapLong(-2);
          oneColumnFamily.put(oneKey, oneValue);
        });

    // then
    assertThat(oneColumnFamily.exists(oneKey)).isTrue();
    assertThat(oneColumnFamily.get(oneKey).getValue()).isEqualTo(-2);
  }
```

The reason for this is that on commit of a transaction it will first process all the writes. After this it will process all the deletes. Therefore the order of the statements in the transactions is lost.

```kotlin
override fun commit() {
        inCurrentTransaction = false
        database.putAll(transactionCache)
        deletedKeys.forEach { database.remove(it) }
        deletedKeys.clear()
        transactionCache.clear()
    }
```

### PR DESCRIPTION
**Pull request by remcowesterhoud**
closes #65 

When putting a key and value in a transaction the key should be removed from the `deletedKeys` cache. Otherwise on commit the value of the key will first be updated, and after this immediately deleted again.

See issue #65 for a more in depth description.

Thanks for letting us copy your code 🙇

### CODE REVIEW

File: eze/src/main/kotlin/org/camunda/community/eze/db/EzeDbTransaction.kt [hunk 1]
```diff
@@ -53,6 +53,8 @@ class EzeDbTransaction(val database : TreeMap<Bytes, Bytes>) : ZeebeDbTransactio
     }
 
     fun put(keyBufferArray: ByteArray, keyLength: Int, valueBufferArray: ByteArray, valueLength: Int) {
+        val keyBytes = keyBufferArray.toBytes(keyLength)
+        deletedKeys.remove(keyBytes)
         transactionCache[keyBufferArray.toBytes(keyLength)] = valueBufferArray.toBytes(valueLength)
```
Comment (Zelldon) [inline eze/src/main/kotlin/org/camunda/community/eze/db/EzeDbTransaction.kt:58]:
```suggestion
        transactionCache[keyBytes] = valueBufferArray.toBytes(valueLength)
```

**Review by Zelldon — APPROVED** [review]
Thanks @remcowesterhoud for finding and fixing it!

TBH: Regarding the copying, it would be cool if you could at least reference the project or something so it is clear where some ideas came from. This would make me happy :)

**Comment by remcowesterhoud** [comment]
Thanks @Zelldon! Sure we can reference this project. I've added it as a todo for when we will write a proper README.
